apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-env-external-secret
spec:
  data:
  # Anthropic API Key
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: ecommerce/anthropic
      metadataPolicy: None
      property: api_key
    secretKey: ANTHROPIC_API_KEY

  # Langfuse credentials
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: ecommerce/langfuse
  #     metadataPolicy: None
  #     property: public_key
  #   secretKey: LANGFUSE_PUBLIC_KEY
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: ecommerce/langfuse
  #     metadataPolicy: None
  #     property: secret_key
  #   secretKey: LANGFUSE_SECRET_KEY
  # - remoteRef:
  #     conversionStrategy: Default
  #     decodingStrategy: None
  #     key: ecommerce/langfuse
  #     metadataPolicy: None
  #     property: host
  #   secretKey: LANGFUSE_BASEURL

  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ai-env-secret
