apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabase-embedding-external-secret
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: ecommerce/metabase
      metadataPolicy: None
      property: embedding_secret_key
    secretKey: METABASE_EMBEDDING_SECRET_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: metabase-embedding-secret
